apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quobyteservices.quobyte.com
spec:
  group: quobyte.com
  names:
    kind: QuobyteService
    plural: quobyteservices
    singular: quobyteservice
    listKind: QuobyteServiceList
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            registry:
              properties:
                daemonSetName:
                nodes:
              required:
                - daemonSetName
                - nodes
            data:
              properties:
                daemonSetName:
                nodes:
              required:
                - daemonSetName
                - nodes
            metadata:
              properties:
                daemonSetName:
                nodes:
              required:
                - daemonSetName
                - nodes