apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quobyteservices.quobyte.com
  namespace: quobyte
spec:
  group: quobyte.com
  names:
    kind: QuobyteService
    plural: quobyteservices
    singular: quobyteservice
    listKind: QuobyteServiceList
  scope: Namespaced
  version: v1