apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quobyteclients.quobyte.com
  namespace: quobyte
spec:
  group: quobyte.com
  names:
    kind: QuobyteClient
    plural: quobyteclients
    singular: quobyteclient
    listKind: QuobyteClientList
  scope: Namespaced
  version: v1