apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quobyteclients.quobyte.com
spec:
  group: quobyte.com
  names:
    kind: QuobyteClient
    plural: quobyteclients
    singular: quobyteclient
    listKind: QuobyteClientList
  scope: Namespaced
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            daemonSetName:
            nodes:
          required:
            - daemonSetName

